Description [ChatGPT, Dictionary API]
LoremIpsumUCD23/HoloLens-Translator pull request #5
Opened 2023-06-14 13:49 UTC by satttto

# PR Details
 

## What this PR is about

## TODOs
- [ ] Have you assigned "reviewers" and "assignees"?
- [ ] Have you written enough comments?
- [ ] Have you written enough tests?
- [ ] Have you tested the behaviour?

## What did you use for verifying your implementation?
- [ ] Unit/Integration tests
- [ ] Unity
- [ ] HoloLens2

## Related links 

- Jira:

2023-06-14 20:49 UTC, satttto commented on Lorem Ipsum XR Translator/Assets/CubeBehavior.cs
> +}
These things will be used later when refactoring the code

2023-06-14 22:19 UTC, aconnolly2 requested changes
Definitely needs some comments.

Would like to see various classes moved to separate class files instead of all mashed into one. A subfolder can be added to scripts folder to keep them organized.

Testing it out, the connection threw an error for me. I suspect this is because the API key is not included. I understand not doing this for security purposes, but if I'm required to get my own API key to test, I'd like to see that made explicit in the comments/documentation.

I also think separate scenes should be made when testing various features instead of using Sample Scene. I made my own scene for my tests, so we won't have a conflict, but if I hadn't, we might have. Eventually we can consolidate all of the various features and aspects into a 'Main Scene,' but we should try to keep our tests a bit more separated until then.

Great work altogether. Would just like to see a bit more documentation before giving my final approval. We can still load this from the branch for testing deployments tomorrow.

2023-06-15 17:11 UTC, satttto commented
@aconnolly2 
Thanks for pointing it out. I've separated Cube behaviours with ChatGPT client. I also created an interface so that we can replace ChatGPT with something else in the future. The interface and implementation for ChatGPT are in Assets->Scripts->Description.

2023-06-15 17:13 UTC, satttto commented on Lorem Ipsum XR Translator/Assets/Scripts/Description/DictionaryAPIClient.cs
> +    }
@Peter-Choah 
Can you implement API calls to a dictionary service here?

2023-06-16 17:11 UTC, satttto commented on Lorem Ipsum XR Translator/Assets/Scripts/Translator/AzureTranslator.cs
> +    //    }
it might be a good idea to clean up this file a little bit by deleting commented out code

2023-06-16 17:12 UTC, satttto commented on Lorem Ipsum XR Translator/Assets/Scripts/Translator/AzureTranslator.cs
> +    //    }
and line 17, 22 and 28

2023-06-16 17:12 UTC, satttto commented on Lorem Ipsum XR Translator/Assets/Scripts/Translator/AzureTranslator.cs
> +    //    }
@VijaydityaSarker

2023-06-21 09:53 UTC, satttto commented on Lorem Ipsum XR Translator/Assets/Scripts/Description/DictionaryAPIClient.cs
> +                        break;
Here, we can change this into something like
```suggestion
                        callback("response: " + webRequest.downloadHandler.text);
                        break;
```

2023-06-21 09:53 UTC, satttto commented on Lorem Ipsum XR Translator/Assets/Scripts/Description/DictionaryAPIClient.cs
> +        }
And comment out all of them

2023-06-29 16:48 UTC, MansiAmbalam approved these changes

2023-07-13 17:28 UTC, merged